name: dozzle
services:
  app:
    container_name: zds-dozzle
    image: amir20/dozzle:v6.5.2
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8888:8080"

    x-casaos:
      volumes:
        - container: /var/run/docker.sock
          description:
            en_us: "Container Path: /var/run/docker.sock"
      ports:
        - container: "8080"
          description:
            en_us: "Container Port: 8080"

x-casaos:
  architectures:
    - amd64
    - arm64
  main: app
  description:
    en_us: Dozzle is a real-time log viewer for docker containers.
  tagline:
    en_us: Dozzle is a real-time log viewer for docker containers.
  developer: "amir20"
  author: ziggyds
  icon: https://github.com/walkxcode/dashboard-icons/blob/main/png/dozzle.png?raw=true
  title:
    en_us: Dozzle
  category: zds
  port_map: "8888"